Repository ChiSym/9.s916-course-materials, pull requests merged in 2025-03, with the labels that each got.

#15 Create lab exercises
  pyproject.toml
  src/lab-exercises.py
  src/localization-tutorial.ipynb
  src/localization-tutorial.py
  src/robot_program.json
  src/world.json
Labels: 30 min review

#17 Add lab exercises
  pixi.lock
  src/lab-exercises.py
  src/localization-tutorial.ipynb
  src/localization-tutorial.py
Labels: 30 min review

#18 Add dm-tree support for osx-64
  pixi.lock
  pyproject.toml
Labels: 5 min review

#21 Add proper lab exercises
  src/lab-exercises-full.ipynb
  src/lab-exercises-full.py
  src/lab-exercises.ipynb
  src/world_small.json
Labels: 30 min review

#23 Problem set edits
  src/lab-exercises-full.ipynb
  src/lab-exercises-full.py
Labels: 1 min review
